var Module=(()=>{var _scriptName=globalThis.document?.currentScript?.src;return async function(moduleArg={}){var moduleRtn;var m=moduleArg,aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca="./this.program";ba&&(_scriptName=self.location.href);var da="",ea,ha;if(aa||ba){try{da=(new URL(".",_scriptName)).href}catch{}ba&&(ha=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});ea=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}
var ia=console.log.bind(console),n=console.error.bind(console),q,ja=!1,ka,la,ma,t,v,z,C,D,F,na,oa,pa,qa,ra=!1;function sa(){var a=ta.buffer;t=new Int8Array(a);z=new Int16Array(a);v=new Uint8Array(a);C=new Uint16Array(a);D=new Int32Array(a);F=new Uint32Array(a);na=new Float32Array(a);oa=new Float64Array(a);pa=new BigInt64Array(a);qa=new BigUint64Array(a)}
function ua(a){m.onAbort?.(a);a="Aborted("+a+")";n(a);ja=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ma?.(a);throw a;}var va;async function wa(a){if(!q)try{var b=await ea(a);return new Uint8Array(b)}catch{}if(a==va&&q)a=new Uint8Array(q);else if(ha)a=ha(a);else throw"both async and sync fetching of the wasm failed";return a}
async function xa(a,b){try{var c=await wa(a);return await WebAssembly.instantiate(c,b)}catch(d){n(`failed to asynchronously prepare wasm: ${d}`),ua(d)}}async function ya(a){var b=va;if(!q)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){n(`wasm streaming compile failed: ${d}`),n("falling back to ArrayBuffer instantiation")}return xa(b,a)}
class za{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Aa=a=>{for(;0<a.length;)a.shift()(m)},Ba=[],Ca=[],Da=()=>{var a=m.preRun.shift();Ca.push(a)},Ea=!0,Fa=globalThis.TextDecoder&&new TextDecoder,Ga=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},G=(a,b=0,c,d)=>{c=Ga(a,b,c,d);if(16<c-b&&a.buffer&&Fa)return Fa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?
d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d};class Ha{constructor(a){this.da=a-24}}var Ia=0,Ja=0,Ka={},La=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function H(a){return this.fa(F[a>>2])}
var I={},J={},Ma={},Na=class extends Error{constructor(a){super(a);this.name="InternalError"}},L=(a,b,c)=>{function d(h){h=c(h);if(h.length!==a.length)throw new Na("Mismatched type converter count");for(var p=0;p<a.length;++p)K(a[p],h[p])}a.forEach(h=>Ma[h]=b);var e=Array(b.length),f=[],g=0;for(let [h,p]of b.entries())J.hasOwnProperty(p)?e[h]=J[p]:(f.push(p),I.hasOwnProperty(p)||(I[p]=[]),I[p].push(()=>{e[h]=J[p];++g;g===f.length&&d(e)}));0===f.length&&d(e)},M=a=>{for(var b="";;){var c=v[a++];if(!c)return b;
b+=String.fromCharCode(c)}},N=class extends Error{constructor(a){super(a);this.name="BindingError"}},Oa=a=>{throw new N(a);};function Pa(a,b,c={}){var d=b.name;if(!a)throw new N(`type "${d}" must have a positive integer typeid pointer`);if(J.hasOwnProperty(a)){if(c.yb)return;throw new N(`Cannot register type '${d}' twice`);}J[a]=b;delete Ma[a];I.hasOwnProperty(a)&&(b=I[a],delete I[a],b.forEach(e=>e()))}function K(a,b,c={}){return Pa(a,b,c)}
var Qa=(a,b,c)=>{switch(b){case 1:return c?d=>t[d]:d=>v[d];case 2:return c?d=>z[d>>1]:d=>C[d>>1];case 4:return c?d=>D[d>>2]:d=>F[d>>2];case 8:return c?d=>pa[d>>3]:d=>qa[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Ra=a=>{throw new N(a.$.ga.ea.name+" instance already deleted");},Sa=!1,Ta=()=>{},O=a=>{if(!globalThis.FinalizationRegistry)return O=b=>b,a;Sa=new FinalizationRegistry(b=>{b=b.$;--b.count.value;0===b.count.value&&(b.ia?b.na.ta(b.ia):b.ga.ea.ta(b.da))});O=b=>
{var c=b.$;c.ia&&Sa.register(b,{$:c},b);return b};Ta=b=>{Sa.unregister(b)};return O(a)},Ua=[];function Va(){}
var Wa=(a,b)=>Object.defineProperty(b,"name",{value:a}),Xa={},Ya=(a,b,c)=>{if(void 0===a[b].wa){var d=a[b];a[b]=function(...e){if(!a[b].wa.hasOwnProperty(e.length))throw new N(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].wa})!`);return a[b].wa[e.length].apply(this,e)};a[b].wa=[];a[b].wa[d.Fa]=d}},Za=(a,b)=>{if(m.hasOwnProperty(a))throw new N(`Cannot register public name '${a}' twice`);m[a]=b;m[a].Fa=void 0},$a=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,
"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function ab(a,b,c,d,e,f,g,h){this.name=a;this.constructor=b;this.Ca=c;this.ta=d;this.ka=e;this.tb=f;this.Ka=g;this.rb=h;this.Cb=[]}var cb=(a,b,c)=>{for(;b!==c;){if(!b.Ka)throw new N(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.Ka(a);b=b.ka}return a},db=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a};
function eb(a,b){if(null===b){if(this.Xa)throw new N(`null is not a valid ${this.name}`);return 0}if(!b.$)throw new N(`Cannot pass "${db(b)}" as a ${this.name}`);if(!b.$.da)throw new N(`Cannot pass deleted object as a pointer of type ${this.name}`);return cb(b.$.da,b.$.ga.ea,this.ea)}
function fb(a,b){if(null===b){if(this.Xa)throw new N(`null is not a valid ${this.name}`);if(this.Oa){var c=this.Za();null!==a&&a.push(this.ta,c);return c}return 0}if(!b||!b.$)throw new N(`Cannot pass "${db(b)}" as a ${this.name}`);if(!b.$.da)throw new N(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.Na&&b.$.ga.Na)throw new N(`Cannot convert argument of type ${b.$.na?b.$.na.name:b.$.ga.name} to parameter type ${this.name}`);c=cb(b.$.da,b.$.ga.ea,this.ea);if(this.Oa){if(void 0===
b.$.ia)throw new N("Passing raw pointer to smart pointer is illegal");switch(this.Hb){case 0:if(b.$.na===this)c=b.$.ia;else throw new N(`Cannot convert argument of type ${b.$.na?b.$.na.name:b.$.ga.name} to parameter type ${this.name}`);break;case 1:c=b.$.ia;break;case 2:if(b.$.na===this)c=b.$.ia;else{var d=b.clone();c=this.Db(c,P(()=>d["delete"]()));null!==a&&a.push(this.ta,c)}break;default:throw new N("Unsupporting sharing policy");}}return c}
function gb(a,b){if(null===b){if(this.Xa)throw new N(`null is not a valid ${this.name}`);return 0}if(!b.$)throw new N(`Cannot pass "${db(b)}" as a ${this.name}`);if(!b.$.da)throw new N(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.$.ga.Na)throw new N(`Cannot convert argument of type ${b.$.ga.name} to parameter type ${this.name}`);return cb(b.$.da,b.$.ga.ea,this.ea)}
var hb=(a,b,c)=>{if(b===c)return a;if(void 0===c.ka)return null;a=hb(a,b,c.ka);return null===a?null:c.rb(a)},ib={},jb=(a,b)=>{if(void 0===b)throw new N("ptr should not be undefined");for(;a.ka;)b=a.Ka(b),a=a.ka;return ib[b]},kb=(a,b)=>{if(!b.ga||!b.da)throw new Na("makeClassHandle requires ptr and ptrType");if(!!b.na!==!!b.ia)throw new Na("Both smartPtrType and smartPtr must be specified");b.count={value:1};return O(Object.create(a,{$:{value:b,writable:!0}}))};
function lb(a,b,c,d,e,f,g,h,p,k,l){this.name=a;this.ea=b;this.Xa=c;this.Na=d;this.Oa=e;this.Bb=f;this.Hb=g;this.lb=h;this.Za=p;this.Db=k;this.ta=l;e||void 0!==b.ka?this.ja=fb:(this.ja=d?eb:gb,this.la=null)}var mb=(a,b)=>{if(!m.hasOwnProperty(a))throw new Na("Replacing nonexistent public symbol");m[a]=b;m[a].Fa=void 0},nb=[],Q=(a,b)=>{a=M(a);var c;(c=nb[b])||(nb[b]=c=ob.get(b));if("function"!=typeof c)throw new N(`unknown function pointer with signature ${a}: ${b}`);return c};
class pb extends Error{}var rb=a=>{a=qb(a);var b=M(a);R(a);return b},sb=(a,b)=>{function c(f){e[f]||J[f]||(Ma[f]?Ma[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new pb(`${a}: `+d.map(rb).join([", "]));},tb=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(F[b+4*d>>2]);return c};function ub(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].la)return!0;return!1}
function vb(a,b,c,d,e,f){var g=b.length;if(2>g)throw new N("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,p=ub(b);c=!b[0].gb;var k=b[0],l=b[1];d=[a,Oa,d,e,La,k.fa.bind(k),l?.ja.bind(l)];for(e=2;e<g;++e)k=b[e],d.push(k.ja.bind(k));if(!p)for(e=h?1:2;e<b.length;++e)null!==b[e].la&&d.push(b[e].la);p=ub(b);e=b.length-2;l=[];k=["fn"];h&&k.push("thisWired");for(g=0;g<e;++g)l.push(`arg${g}`),k.push(`arg${g}Wired`);l=l.join(",");k=k.join(",");
l=`return function (${l}) {\n`;p&&(l+="var destructors = [];\n");var u=p?"destructors":"null",r="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");h&&(l+=`var thisWired = toClassParamWire(${u}, this);\n`);for(g=0;g<e;++g){var w=`toArg${g}Wire`;l+=`var arg${g}Wired = ${w}(${u}, arg${g});\n`;r.push(w)}l+=(c||f?"var rv = ":"")+`invoker(${k});\n`;if(p)l+="runDestructors(destructors);\n";else for(g=h?1:2;g<b.length;++g)f=1===g?"thisWired":"arg"+(g-2)+"Wired",
null!==b[g].la&&(l+=`${f}_dtor(${f});\n`,r.push(`${f}_dtor`));c&&(l+="var ret = fromRetWire(rv);\nreturn ret;\n");b=(new Function(r,l+"}\n"))(...d);return Wa(a,b)}
var wb=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},xb=[],S=[0,1,,1,null,1,!0,1,!1,1],yb=a=>{9<a&&0===--S[a+1]&&(S[a]=void 0,xb.push(a))},zb=a=>{if(!a)throw new N(`Cannot use deleted val. handle = ${a}`);return S[a]},P=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=xb.pop()||S.length;S[b]=a;S[b+1]=1;return b}},Ab={name:"emscripten::val",fa:a=>{var b=zb(a);yb(a);return b},ja:(a,b)=>P(b),qa:H,la:null},Bb=(a,b,c)=>{switch(b){case 1:return c?
function(d){return this.fa(t[d])}:function(d){return this.fa(v[d])};case 2:return c?function(d){return this.fa(z[d>>1])}:function(d){return this.fa(C[d>>1])};case 4:return c?function(d){return this.fa(D[d>>2])}:function(d){return this.fa(F[d>>2])};default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Cb=(a,b)=>{var c=J[a];if(void 0===c)throw a=`${b} has unknown type ${rb(a)}`,new N(a);return c},Db=(a,b)=>{switch(b){case 4:return function(c){return this.fa(na[c>>2])};case 8:return function(c){return this.fa(oa[c>>
3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Eb=Object.assign({optional:!0},Ab),T=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(c>=d)break;b[c++]=g}else if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-
e},Fb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Gb=globalThis.TextDecoder?new TextDecoder("utf-16le"):void 0,Hb=(a,b,c)=>{a>>=1;b=Ga(C,a,b/2,c);if(16<b-a&&Gb)return Gb.decode(C.subarray(a,b));for(c="";a<b;++a)c+=String.fromCharCode(C[a]);return c},Ib=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)z[b>>1]=a.charCodeAt(e),b+=2;z[b>>1]=0;return b-d},Jb=a=>2*a.length,
Kb=(a,b,c)=>{var d="";a>>=2;for(var e=0;!(e>=b/4);e++){var f=F[a+e];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},Lb=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.codePointAt(e);65535<f&&e++;D[b>>2]=f;b+=4;if(b+4>c)break}D[b>>2]=0;return b-d},Mb=a=>{for(var b=0,c=0;c<a.length;++c)65535<a.codePointAt(c)&&c++,b+=4;return b},Nb=0,Ob=[],Pb=a=>{var b=Ob.length;Ob.push(a);return b},Qb=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=Cb(F[b+4*d>>2],`parameter ${d}`);
return c},Rb=(a,b,c)=>{var d=[];a=a(d,c);d.length&&(F[b>>2]=P(d));return a},Sb={},Tb=a=>{var b=Sb[a];return void 0===b?M(a):b},Ub={},Vb=a=>{if(!(a instanceof za||"unwind"==a))throw a;},Wb=a=>{ka=a;Ea||0<Nb||(m.onExit?.(a),ja=!0);throw new za(a);},Xb=a=>{if(!ja)try{if(a(),!(Ea||0<Nb))try{ka=a=ka,Wb(a)}catch(b){Vb(b)}}catch(b){Vb(b)}},Yb={},$b=()=>{if(!Zb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",
_:ca||"./this.program"},b;for(b in Yb)void 0===Yb[b]?delete a[b]:a[b]=Yb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Zb=c}return Zb},Zb,ac=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},bc=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=ac(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},dc=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);
a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},ec=()=>a=>crypto.getRandomValues(a),fc=a=>{(fc=ec())(a)},gc=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=ac(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},hc=[],ic=[];function jc(a,b){ic[a]={input:[],output:[],Ea:b};kc(a,lc)}
var lc={open(a){var b=ic[a.node.Ra];if(!b)throw new U(43);a.oa=b;a.seekable=!1},close(a){a.oa.Ea.Ma(a.oa)},Ma(a){a.oa.Ea.Ma(a.oa)},read(a,b,c,d){if(!a.oa||!a.oa.Ea.fb)throw new U(60);for(var e=0,f=0;f<d;f++){try{var g=a.oa.Ea.fb(a.oa)}catch(h){throw new U(29);}if(void 0===g&&0===e)throw new U(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.ya=Date.now());return e},write(a,b,c,d){if(!a.oa||!a.oa.Ea.Ya)throw new U(60);try{for(var e=0;e<d;e++)a.oa.Ea.Ya(a.oa,b[c+e])}catch(f){throw new U(29);
}d&&(a.node.pa=a.node.ma=Date.now());return e}},mc={fb(){a:{if(!hc.length){var a=null;globalThis.window?.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){var b=null;break a}b=Array(Fb(a)+1);a=T(a,b,0,b.length);b.length=a;hc=b}b=hc.shift()}return b},Ya(a,b){null===b||10===b?(ia(G(a.output)),a.output=[]):0!=b&&a.output.push(b)},Ma(a){0<a.output?.length&&(ia(G(a.output)),a.output=[])},Vb(){return{Nb:25856,Pb:5,Mb:191,Ob:35387,Lb:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0]}},Wb(){return 0},Xb(){return[24,80]}},nc={Ya(a,b){null===b||10===b?(n(G(a.output)),a.output=[]):0!=b&&a.output.push(b)},Ma(a){0<a.output?.length&&(n(G(a.output)),a.output=[])}},V={sa:null,va(){return V.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new U(63);V.sa||(V.sa={dir:{node:{xa:V.ba.xa,ua:V.ba.ua,Ha:V.ba.Ha,Pa:V.ba.Pa,mb:V.ba.mb,ob:V.ba.ob,nb:V.ba.nb,$a:V.ba.$a,Sa:V.ba.Sa},stream:{ra:V.ca.ra}},file:{node:{xa:V.ba.xa,ua:V.ba.ua},
stream:{ra:V.ca.ra,read:V.ca.read,write:V.ca.write,ib:V.ca.ib,kb:V.ca.kb}},link:{node:{xa:V.ba.xa,ua:V.ba.ua,Ja:V.ba.Ja},stream:{}},bb:{node:{xa:V.ba.xa,ua:V.ba.ua},stream:oc}});c=pc(a,b,c,d);16384===(c.mode&61440)?(c.ba=V.sa.dir.node,c.ca=V.sa.dir.stream,c.aa={}):32768===(c.mode&61440)?(c.ba=V.sa.file.node,c.ca=V.sa.file.stream,c.ha=0,c.aa=null):40960===(c.mode&61440)?(c.ba=V.sa.link.node,c.ca=V.sa.link.stream):8192===(c.mode&61440)&&(c.ba=V.sa.bb.node,c.ca=V.sa.bb.stream);c.ya=c.pa=c.ma=Date.now();
a&&(a.aa[b]=c,a.ya=a.pa=a.ma=c.ya);return c},Sb(a){return a.aa?a.aa.subarray?a.aa.subarray(0,a.ha):new Uint8Array(a.aa):new Uint8Array(0)},ba:{xa(a){var b={};b.Qb=8192===(a.mode&61440)?a.id:1;b.Ub=a.id;b.mode=a.mode;b.Yb=1;b.uid=0;b.Tb=0;b.Ra=a.Ra;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.ha:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.ya=new Date(a.ya);b.pa=new Date(a.pa);b.ma=new Date(a.ma);b.pb=4096;b.Kb=Math.ceil(b.size/b.pb);return b},ua(a,b){for(var c of["mode",
"atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.ha!=b&&(0==b?(a.aa=null,a.ha=0):(c=a.aa,a.aa=new Uint8Array(b),c&&a.aa.set(c.subarray(0,Math.min(b,a.ha))),a.ha=b)))},Ha(){V.Ta||(V.Ta=new U(44),V.Ta.stack="<generic error, no stack>");throw V.Ta;},Pa(a,b,c,d){return V.createNode(a,b,c,d)},mb(a,b,c){try{var d=qc(b,c)}catch(f){}if(d){if(16384===(a.mode&61440))for(var e in d.aa)throw new U(55);e=rc(d.parent.id,d.name);if(W[e]===d)W[e]=d.Da;else for(e=W[e];e;){if(e.Da===d){e.Da=
d.Da;break}e=e.Da}}delete a.parent.aa[a.name];b.aa[c]=a;a.name=c;b.ma=b.pa=a.parent.ma=a.parent.pa=Date.now()},ob(a,b){delete a.aa[b];a.ma=a.pa=Date.now()},nb(a,b){var c=qc(a,b),d;for(d in c.aa)throw new U(55);delete a.aa[b];a.ma=a.pa=Date.now()},$a(a){return[".","..",...Object.keys(a.aa)]},Sa(a,b,c){a=V.createNode(a,b,41471,0);a.link=c;return a},Ja(a){if(40960!==(a.mode&61440))throw new U(28);return a.link}},ca:{read(a,b,c,d,e){var f=a.node.aa;if(e>=a.node.ha)return 0;a=Math.min(a.node.ha-e,d);if(8<
a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===t.buffer&&(f=!1);if(!d)return 0;a=a.node;a.pa=a.ma=Date.now();if(b.subarray&&(!a.aa||a.aa.subarray)){if(f)return a.aa=b.subarray(c,c+d),a.ha=d;if(0===a.ha&&0===e)return a.aa=b.slice(c,c+d),a.ha=d;if(e+d<=a.ha)return a.aa.set(b.subarray(c,c+d),e),d}f=e+d;var g=a.aa?a.aa.length:0;g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>0),0!=g&&(f=Math.max(f,256)),g=a.aa,a.aa=new Uint8Array(f),0<a.ha&&
a.aa.set(g.subarray(0,a.ha),0));if(a.aa.subarray&&b.subarray)a.aa.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.aa[e+f]=b[c+f];a.ha=Math.max(a.ha,e+d);return d},ra(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.ha);if(0>b)throw new U(28);return b},ib(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new U(43);a=a.node.aa;if(e&2||!a||a.buffer!==t.buffer){d=!0;ua();e=void 0;if(!e)throw new U(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,
c,c+b);t.set(a,e)}}else d=!1,e=a.byteOffset;return{da:e,Jb:d}},kb(a,b,c,d){V.ca.write(a,b,0,d,c,!1);return 0}}},sc=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},tc=null,uc={},vc=[],wc=1,W=null,xc=!1,yc=!0,zc={},U=class{name="ErrnoError";constructor(a){this.Aa=a}},Ac=class{La={};node=null;get flags(){return this.La.flags}set flags(a){this.La.flags=a}get position(){return this.La.position}set position(a){this.La.position=a}},Bc=class{ba={};ca={};Qa=null;constructor(a,b,c,d){a||=this;this.parent=
a;this.va=a.va;this.id=wc++;this.name=b;this.mode=c;this.Ra=d;this.ya=this.pa=this.ma=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}};
function X(a,b={}){if(!a)throw new U(44);b.Va??(b.Va=!0);"/"===a.charAt(0)||(a="//"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(h=>!!h);for(var d=tc,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if("."!==a[f])if(".."===a[f])if(e=dc(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=bc(e+"/"+a[f]);try{d=qc(d,a[f])}catch(h){if(44===h?.Aa&&g&&b.Ab)return{path:e};throw h;}!d.Qa||g&&!b.Va||(d=d.Qa.root);if(40960===(d.mode&61440)&&(!g||b.Ua)){if(!d.ba.Ja)throw new U(52);
d=d.ba.Ja(d);"/"===d.charAt(0)||(d=dc(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new U(32);}function rc(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%W.length}function qc(a,b){var c=16384===(a.mode&61440)?(c=Cc(a,"x"))?c:a.ba.Ha?0:2:54;if(c)throw new U(c);for(c=W[rc(a.id,b)];c;c=c.Da){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.ba.Ha(a,b)}
function pc(a,b,c,d){a=new Bc(a,b,c,d);b=rc(a.parent.id,a.name);a.Da=W[b];return W[b]=a}function Dc(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Cc(a,b){if(yc)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Ec(a,b){if(16384!==(a.mode&61440))return 54;try{return qc(a,b),20}catch(c){}return Cc(a,"wx")}function Fc(a){a=vc[a];if(!a)throw new U(8);return a}
function Gc(a,b){var c=null?.ca.ua,d=c?null:a;c??=a.ba.ua;if(!c)throw new U(63);c(d,b)}var oc={open(a){a.ca=uc[a.node.Ra].ca;a.ca.open?.(a)},ra(){throw new U(70);}};function kc(a,b){uc[a]={ca:b}}function Hc(a,b){var c="/"===b;if(c&&tc)throw new U(10);if(!c&&b){var d=X(b,{Va:!1});b=d.path;d=d.node;if(d.Qa)throw new U(10);if(16384!==(d.mode&61440))throw new U(54);}b={type:a,Zb:{},jb:b,zb:[]};a=a.va(b);a.va=b;b.root=a;c?tc=a:d&&(d.Qa=b,d.va&&d.va.zb.push(b))}
function Ic(a,b,c){var d=X(a,{parent:!0}).node;a=a&&a.match(/([^\/]+|\/)\/*$/)[1];if(!a)throw new U(28);if("."===a||".."===a)throw new U(20);var e=Ec(d,a);if(e)throw new U(e);if(!d.ba.Pa)throw new U(63);return d.ba.Pa(d,a,b,c)}function Y(a){return Ic(a,16895,0)}function Jc(a,b,c){"undefined"==typeof c&&(c=b,b=438);Ic(a,b|8192,c)}
function Kc(a,b){if(!gc(a))throw new U(44);var c=X(b,{parent:!0}).node;if(!c)throw new U(44);b=b&&b.match(/([^\/]+|\/)\/*$/)[1];var d=Ec(c,b);if(d)throw new U(d);if(!c.ba.Sa)throw new U(63);c.ba.Sa(c,b,a)}
function Lc(a,b){if(""===a)throw new U(44);if("string"==typeof b){var c={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof c)throw Error(`Unknown file open mode: ${b}`);b=c}c=b&64?33206:0;if("object"==typeof a)var d=a;else{var e=a.endsWith("/");a=X(a,{Ua:!(b&131072),Ab:!0});d=a.node;a=a.path}var f=!1;if(b&64)if(d){if(b&128)throw new U(20);}else{if(e)throw new U(31);d=Ic(a,c|511,0);f=!0}if(!d)throw new U(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&16384!==(d.mode&61440))throw new U(54);
if(!f&&(e=d?40960===(d.mode&61440)?32:16384===(d.mode&61440)&&("r"!==Dc(b)||b&576)?31:Cc(d,Dc(b)):44))throw new U(e);if(b&512&&!f){e=d;e="string"==typeof e?X(e,{Ua:!0}).node:e;if(16384===(e.mode&61440))throw new U(31);if(32768!==(e.mode&61440))throw new U(28);var g=Cc(e,"w");if(g)throw new U(g);Gc(e,{size:0,timestamp:Date.now()})}b&=-131713;a:for(e=d;;){if(e===e.parent){e=e.va.jb;var h=h?"/"!==e[e.length-1]?`${e}/${h}`:e+h:e;break a}h=h?`${e.name}/${h}`:e.name;e=e.parent}h={node:d,path:h,flags:b,
seekable:!0,position:0,ca:d.ca,Ib:[],error:!1};e=-1;h=Object.assign(new Ac,h);if(-1==e)a:{for(e=0;4096>=e;e++)if(!vc[e])break a;throw new U(33);}h.Ba=e;vc[e]=h;h.ca.open&&h.ca.open(h);f&&(c&=511,d="string"==typeof d?X(d,{Ua:!0}).node:d,Gc(d,{mode:c&4095|d.mode&-4096,ma:Date.now(),Rb:void 0}));!m.logReadFiles||b&1||a in zc||(zc[a]=1)}function Mc(a,b,c){if(null===a.Ba)throw new U(8);if(!a.seekable||!a.ca.ra)throw new U(70);if(0!=c&&1!=c&&2!=c)throw new U(28);a.position=a.ca.ra(a,b,c);a.Ib=[]}
function Z(a,b,c){a=bc("/dev/"+a);var d=sc(!!b,!!c);Z.hb??(Z.hb=64);var e=Z.hb++<<8|0;kc(e,{open(f){f.seekable=!1},close(){c?.buffer?.length&&c(10)},read(f,g,h,p){for(var k=0,l=0;l<p;l++){try{var u=b()}catch(r){throw new U(29);}if(void 0===u&&0===k)throw new U(6);if(null===u||void 0===u)break;k++;g[h+l]=u}k&&(f.node.ya=Date.now());return k},write(f,g,h,p){for(var k=0;k<p;k++)try{c(g[h+k])}catch(l){throw new U(29);}p&&(f.node.pa=f.node.ma=Date.now());return k}});Jc(a,d,e)}
var Nc={},Rc=(a,b,c,d)=>{var e={string:k=>{var l=0;if(null!==k&&void 0!==k&&0!==k){l=Fb(k)+1;var u=Oc(l);T(k,v,u,l);l=u}return l},array:k=>{var l=Oc(k.length);t.set(k,l);return l}};a=m["_"+a];var f=[],g=0;if(d)for(var h=0;h<d.length;h++){var p=e[c[h]];p?(0===g&&(g=Pc()),f[h]=p(d[h])):f[h]=d[h]}c=a(...f);return c=function(k){0!==g&&Qc(g);return"string"===b?k?G(v,k):"":"boolean"===b?!!k:k}(c)};
(()=>{let a=Va.prototype;Object.assign(a,{isAliasOf:function(c){if(!(this instanceof Va&&c instanceof Va))return!1;var d=this.$.ga.ea,e=this.$.da;c.$=c.$;var f=c.$.ga.ea;for(c=c.$.da;d.ka;)e=d.Ka(e),d=d.ka;for(;f.ka;)c=f.Ka(c),f=f.ka;return d===f&&e===c},clone:function(){this.$.da||Ra(this);if(this.$.Ia)return this.$.count.value+=1,this;var c=O,d=Object,e=d.create,f=Object.getPrototypeOf(this),g=this.$;c=c(e.call(d,f,{$:{value:{count:g.count,Ga:g.Ga,Ia:g.Ia,da:g.da,ga:g.ga,ia:g.ia,na:g.na}}}));c.$.count.value+=
1;c.$.Ga=!1;return c},["delete"](){this.$.da||Ra(this);if(this.$.Ga&&!this.$.Ia)throw new N("Object already scheduled for deletion");Ta(this);var c=this.$;--c.count.value;0===c.count.value&&(c.ia?c.na.ta(c.ia):c.ga.ea.ta(c.da));this.$.Ia||(this.$.ia=void 0,this.$.da=void 0)},isDeleted:function(){return!this.$.da},deleteLater:function(){this.$.da||Ra(this);if(this.$.Ga&&!this.$.Ia)throw new N("Object already scheduled for deletion");Ua.push(this);this.$.Ga=!0;return this}});const b=Symbol.dispose;
b&&(a[b]=a["delete"])})();
Object.assign(lb.prototype,{ub(a){this.lb&&(a=this.lb(a));return a},cb(a){this.ta?.(a)},qa:H,fa:function(a){function b(){return this.Oa?kb(this.ea.Ca,{ga:this.Bb,da:c,na:this,ia:a}):kb(this.ea.Ca,{ga:this,da:a})}var c=this.ub(a);if(!c)return this.cb(a),null;var d=jb(this.ea,c);if(void 0!==d){if(0===d.$.count.value)return d.$.da=c,d.$.ia=a,d.clone();d=d.clone();this.cb(a);return d}d=this.ea.tb(c);d=Xa[d];if(!d)return b.call(this);d=this.Na?d.qb:d.pointerType;var e=hb(c,this.ea,d.ea);return null===
e?b.call(this):this.Oa?kb(d.ea.Ca,{ga:d,da:e,na:this,ia:a}):kb(d.ea.Ca,{ga:d,da:e})}});W=Array(4096);Hc(V,"/");Y("/tmp");Y("/home");Y("/home/web_user");(function(){Y("/dev");kc(259,{read:()=>0,write:(d,e,f,g)=>g,ra:()=>0});Jc("/dev/null",259);jc(1280,mc);jc(1536,nc);Jc("/dev/tty",1280);Jc("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(fc(a),b=a.byteLength);return a[--b]};Z("random",c);Z("urandom",c);Y("/dev/shm");Y("/dev/shm/tmp")})();
(function(){Y("/proc");var a=Y("/proc/self");Y("/proc/self/fd");Hc({va(){var b=pc(a,"fd",16895,73);b.ca={ra:V.ca.ra};b.ba={Ha(c,d){c=+d;var e=Fc(c);c={parent:null,va:{jb:"fake"},ba:{Ja:()=>e.path},id:c+1};return c.parent=c},$a(){return Array.from(vc.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();m.noExitRuntime&&(Ea=m.noExitRuntime);m.print&&(ia=m.print);m.printErr&&(n=m.printErr);m.wasmBinary&&(q=m.wasmBinary);m.thisProgram&&(ca=m.thisProgram);
if(m.preInit)for("function"==typeof m.preInit&&(m.preInit=[m.preInit]);0<m.preInit.length;)m.preInit.shift()();m.ccall=Rc;m.cwrap=(a,b,c,d)=>{var e=!c||c.every(f=>"number"===f||"boolean"===f);return"string"!==b&&e&&!d?m["_"+a]:(...f)=>Rc(a,b,c,f,d)};
var qb,Sc,Tc,Uc,R,Qc,Oc,Pc,ta,ob,Vc={k:(a,b,c,d)=>ua(`Assertion failed: ${a?G(v,a):""}, at: `+[b?b?G(v,b):"":"unknown filename",c,d?d?G(v,d):"":"unknown function"]),o:(a,b,c)=>{var d=new Ha(a);F[d.da+16>>2]=0;F[d.da+4>>2]=b;F[d.da+8>>2]=c;Ia=a;Ja++;throw Ia;},D:()=>ua(""),g:a=>{var b=Ka[a];delete Ka[a];var c=b.Za,d=b.ta,e=b.eb,f=e.map(g=>g.xb).concat(e.map(g=>g.Fb));L([a],f,g=>{var h={},p,k;for([p,k]of e.entries()){const l=g[p],u=k.vb,r=k.wb,w=g[p+e.length],x=k.Eb,B=k.Gb;h[k.sb]={read:A=>l.fa(u(r,
A)),write:(A,E)=>{var y=[];x(B,A,w.ja(y,E));La(y)},optional:l.optional}}return[{name:b.name,fa:l=>{var u={},r;for(r in h)u[r]=h[r].read(l);d(l);return u},ja:(l,u)=>{for(var r in h)if(!(r in u||h[r].optional))throw new TypeError(`Missing field: "${r}"`);var w=c();for(r in h)h[r].write(w,u[r]);null!==l&&l.push(d,w);return w},qa:H,la:d}]})},t:(a,b,c,d,e)=>{b=M(b);d=0n===d;let f=g=>g;if(d){const g=8*c;f=h=>BigInt.asUintN(g,h);e=f(e)}K(a,{name:b,fa:f,ja:(g,h)=>{"number"==typeof h&&(h=BigInt(h));return h},
qa:Qa(b,c,!d),la:null})},P:(a,b,c,d)=>{b=M(b);K(a,{name:b,fa:function(e){return!!e},ja:function(e,f){return f?c:d},qa:function(e){return this.fa(v[e])},la:null})},i:(a,b,c,d,e,f,g,h,p,k,l,u,r)=>{l=M(l);f=Q(e,f);h&&=Q(g,h);k&&=Q(p,k);r=Q(u,r);var w=$a(l);Za(w,function(){sb(`Cannot construct ${l} due to unbound types`,[d])});L([a,b,c],d?[d]:[],x=>{x=x[0];if(d){var B=x.ea;var A=B.Ca}else A=Va.prototype;x=Wa(l,function(...bb){if(Object.getPrototypeOf(this)!==E)throw new N(`Use 'new' to construct ${l}`);
if(void 0===y.za)throw new N(`${l} has no accessible constructor`);var cc=y.za[bb.length];if(void 0===cc)throw new N(`Tried to invoke ctor of ${l} with invalid number of parameters (${bb.length}) - expected (${Object.keys(y.za).toString()}) parameters instead!`);return cc.apply(this,bb)});var E=Object.create(A,{constructor:{value:x}});x.prototype=E;var y=new ab(l,x,E,r,B,f,h,k);if(y.ka){var fa;(fa=y.ka).ab??(fa.ab=[]);y.ka.ab.push(y)}B=new lb(l,y,!0,!1,!1);fa=new lb(l+"*",y,!1,!1,!1);A=new lb(l+" const*",
y,!1,!0,!1);Xa[a]={pointerType:fa,qb:A};mb(w,x);return[B,fa,A]})},j:(a,b,c,d,e,f)=>{var g=tb(b,c);e=Q(d,e);L([],[a],h=>{h=h[0];var p=`constructor ${h.name}`;void 0===h.ea.za&&(h.ea.za=[]);if(void 0!==h.ea.za[b-1])throw new N(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${h.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);h.ea.za[b-1]=()=>{sb(`Cannot construct ${h.name} due to unbound types`,
g)};L([],g,k=>{k.splice(1,0,null);h.ea.za[b-1]=vb(p,k,null,e,f);return[]});return[]})},a:(a,b,c,d,e,f,g,h,p)=>{var k=tb(c,d);b=M(b);b=wb(b);f=Q(e,f);L([],[a],l=>{function u(){sb(`Cannot call ${r} due to unbound types`,k)}l=l[0];var r=`${l.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);h&&l.ea.Cb.push(b);var w=l.ea.Ca,x=w[b];void 0===x||void 0===x.wa&&x.className!==l.name&&x.Fa===c-2?(u.Fa=c-2,u.className=l.name,w[b]=u):(Ya(w,b,r),w[b].wa[c-2]=u);L([],k,B=>{B=vb(r,B,l,f,g,p);void 0===w[b].wa?
(B.Fa=c-2,w[b]=B):w[b].wa[c-2]=B;return[]});return[]})},N:a=>K(a,Ab),m:(a,b,c,d)=>{function e(){}b=M(b);e.values={};K(a,{name:b,constructor:e,fa:function(f){return this.constructor.values[f]},ja:(f,g)=>g.value,qa:Bb(b,c,d),la:null});Za(b,e)},l:(a,b,c)=>{var d=Cb(a,"enum");b=M(b);a=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:Wa(`${d.name}_${b}`,function(){})}});a.values[c]=d;a[b]=d},s:(a,b,c)=>{b=M(b);K(a,{name:b,fa:d=>d,ja:(d,e)=>e,qa:Db(b,c),la:null})},
f:(a,b,c,d,e)=>{b=M(b);let f=h=>h;if(0===d){var g=32-8*c;f=h=>h<<g>>>g;e=f(e)}K(a,{name:b,fa:f,ja:(h,p)=>p,qa:Qa(b,c,0!==d),la:null})},b:(a,b,c)=>{function d(f){return new e(t.buffer,F[f+4>>2],F[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=M(c);K(a,{name:c,fa:d,qa:d},{yb:!0})},q:a=>{K(a,Eb)},O:(a,b)=>{b=M(b);K(a,{name:b,fa(c){var d=(d=c+4)?G(v,d,F[c>>2],!0):"";R(c);return d},ja(c,d){d instanceof ArrayBuffer&&
(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new N("Cannot pass non-string to std::string");var f=e?Fb(d):d.length;var g=Tc(4+f+1),h=g+4;F[g>>2]=f;e?T(d,v,h,f+1):v.set(d,h);null!==c&&c.push(R,g);return g},qa:H,la(c){R(c)}})},n:(a,b,c)=>{c=M(c);if(2===b){var d=Hb;var e=Ib;var f=Jb}else d=Kb,e=Lb,f=Mb;K(a,{name:c,fa:g=>{var h=d(g+4,F[g>>2]*b,!0);R(g);return h},ja:(g,h)=>{if("string"!=typeof h)throw new N(`Cannot pass non-string to C++ string type ${c}`);
var p=f(h),k=Tc(4+p+b);F[k>>2]=p/b;e(h,k+4,p+b);null!==g&&g.push(R,k);return k},qa:H,la(g){R(g)}})},h:(a,b,c,d,e,f)=>{Ka[a]={name:M(b),Za:Q(c,d),ta:Q(e,f),eb:[]}},c:(a,b,c,d,e,f,g,h,p,k)=>{Ka[a].eb.push({sb:M(b),xb:c,vb:Q(d,e),wb:f,Fb:g,Eb:Q(h,p),Gb:k})},u:(a,b)=>{b=M(b);K(a,{gb:!0,name:b,fa:()=>{},ja:()=>{}})},x:()=>{Ea=!1;Nb=0},e:(a,b,c)=>{var [d,...e]=Qb(a,b);b=d.ja.bind(d);var f=e.map(p=>p.qa.bind(p));a--;var g={toValue:zb};a=f.map((p,k)=>{var l=`argFromPtr${k}`;g[l]=p;return`${l}(args${k?"+"+
8*k:""})`});switch(c){case 0:var h="toValue(handle)";break;case 2:h="new (toValue(handle))";break;case 3:h="";break;case 1:g.getStringOrSymbol=Tb,h="toValue(handle)[getStringOrSymbol(methodName)]"}h+=`(${a})`;d.gb||(g.toReturnWire=b,g.emval_returnValue=Rb,h=`return emval_returnValue(toReturnWire, destructorsRef, ${h})`);h=`return function (handle, methodName, destructorsRef, args) {\n  ${h}\n  }`;c=(new Function(Object.keys(g),h))(...Object.values(g));h=`methodCaller<(${e.map(p=>p.name)}) => ${d.name}>`;
return Pb(Wa(h,c))},I:yb,M:a=>{if(!a)return P(globalThis);a=Tb(a);return P(globalThis[a])},r:(a,b)=>{a=zb(a);b=zb(b);return P(a[b])},p:a=>{9<a&&(S[a+1]+=1)},d:(a,b,c,d,e)=>Ob[a](b,c,d,e),L:a=>P(Tb(a)),v:a=>{var b=zb(a);La(b);yb(a)},y:(a,b)=>{Ub[a]&&(clearTimeout(Ub[a].id),delete Ub[a]);if(!b)return 0;var c=setTimeout(()=>{delete Ub[a];Xb(()=>Uc(a,performance.now()))},b);Ub[a]={id:c,$b:b};return 0},A:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,
1)).getTimezoneOffset();F[a>>2]=60*Math.max(f,e);D[b>>2]=Number(f!=e);b=g=>{var h=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(h/60)).padStart(2,"0")}${String(h%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(T(a,v,c,17),T(b,v,d,17)):(T(a,v,d,17),T(b,v,c,17))},H:function(a,b,c){if(!(0<=a&&3>=a))return 28;pa[c>>3]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));return 0},J:a=>{var b=v.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);
a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-ta.buffer.byteLength+65535)/65536|0;try{ta.grow(d);sa();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},B:(a,b)=>{var c=0,d=0,e;for(e of $b()){var f=b+c;F[a+d>>2]=f;c+=T(e,v,f,Infinity)+1;d+=4}return 0},C:(a,b)=>{var c=$b();F[a>>2]=c.length;a=0;for(var d of c)a+=Fb(d)+1;F[b>>2]=a;return 0},E:function(a){try{var b=Fc(a);if(null===b.Ba)throw new U(8);b.Wa&&(b.Wa=null);try{b.ca.close&&b.ca.close(b)}catch(c){throw c;}finally{vc[b.Ba]=
null}b.Ba=null;return 0}catch(c){if("undefined"==typeof Nc||"ErrnoError"!==c.name)throw c;return c.Aa}},G:function(a,b,c,d){try{a:{var e=Fc(a);a=b;for(var f,g=b=0;g<c;g++){var h=F[a>>2],p=F[a+4>>2];a+=8;var k=e,l=h,u=p,r=f,w=t;if(0>u||0>r)throw new U(28);if(null===k.Ba)throw new U(8);if(1===(k.flags&2097155))throw new U(8);if(16384===(k.node.mode&61440))throw new U(31);if(!k.ca.read)throw new U(28);var x="undefined"!=typeof r;if(!x)r=k.position;else if(!k.seekable)throw new U(70);var B=k.ca.read(k,
w,l,u,r);x||(k.position+=B);var A=B;if(0>A){var E=-1;break a}b+=A;if(A<p)break;"undefined"!=typeof f&&(f+=A)}E=b}F[d>>2]=E;return 0}catch(y){if("undefined"==typeof Nc||"ErrnoError"!==y.name)throw y;return y.Aa}},F:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=Fc(a);Mc(e,b,c);pa[d>>3]=BigInt(e.position);e.Wa&&0===b&&0===c&&(e.Wa=null);return 0}catch(f){if("undefined"==typeof Nc||"ErrnoError"!==f.name)throw f;return f.Aa}},K:function(a,b,c,
d){try{a:{var e=Fc(a);a=b;for(var f,g=b=0;g<c;g++){var h=F[a>>2],p=F[a+4>>2];a+=8;var k=e,l=h,u=p,r=f,w=t;if(0>u||0>r)throw new U(28);if(null===k.Ba)throw new U(8);if(0===(k.flags&2097155))throw new U(8);if(16384===(k.node.mode&61440))throw new U(31);if(!k.ca.write)throw new U(28);k.seekable&&k.flags&1024&&Mc(k,0,2);var x="undefined"!=typeof r;if(!x)r=k.position;else if(!k.seekable)throw new U(70);var B=k.ca.write(k,w,l,u,r,void 0);x||(k.position+=B);var A=B;if(0>A){var E=-1;break a}b+=A;if(A<p)break;
"undefined"!=typeof f&&(f+=A)}E=b}F[d>>2]=E;return 0}catch(y){if("undefined"==typeof Nc||"ErrnoError"!==y.name)throw y;return y.Aa}},w:Wb,z:function(a,b){try{return fc(v.subarray(a,a+b)),0}catch(c){if("undefined"==typeof Nc||"ErrnoError"!==c.name)throw c;return c.Aa}}},Wc;
Wc=await (async function(){function a(c){c=Wc=c.exports;qb=c.S;Sc=m._main=c.T;Tc=c.V;Uc=c.W;R=c.X;Qc=c.Y;Oc=c.Z;Pc=c._;ta=c.Q;ob=c.U;sa();return Wc}var b={a:Vc};if(m.instantiateWasm)return new Promise(c=>{m.instantiateWasm(b,(d,e)=>{c(a(d,e))})});va??=m.locateFile?m.locateFile("splendor.wasm",da):da+"splendor.wasm";return a((await ya(b)).instance)}());
(function(){function a(){m.calledRun=!0;if(!ja){ra=!0;if(!m.noFSInit&&!xc){var b,c;xc=!0;b??=m.stdin;c??=m.stdout;d??=m.stderr;b?Z("stdin",b):Kc("/dev/tty","/dev/stdin");c?Z("stdout",null,c):Kc("/dev/tty","/dev/stdout");d?Z("stderr",null,d):Kc("/dev/tty1","/dev/stderr");Lc("/dev/stdin",0);Lc("/dev/stdout",1);Lc("/dev/stderr",1)}Wc.R();yc=!1;la?.(m);m.onRuntimeInitialized?.();if(!m.noInitialRun){var d=Sc;try{var e=d(0,0);ka=e;Wb(e)}catch(f){Vb(f)}}if(m.postRun)for("function"==typeof m.postRun&&(m.postRun=
[m.postRun]);m.postRun.length;)e=m.postRun.shift(),Ba.push(e);Aa(Ba)}}if(m.preRun)for("function"==typeof m.preRun&&(m.preRun=[m.preRun]);m.preRun.length;)Da();Aa(Ca);m.setStatus?(m.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>m.setStatus(""),1);a()},1)):a()})();ra?moduleRtn=m:moduleRtn=new Promise((a,b)=>{la=a;ma=b});
;return moduleRtn}})();if(typeof exports==="object"&&typeof module==="object"){module.exports=Module;module.exports.default=Module}else if(typeof define==="function"&&define["amd"])define([],()=>Module);
