var Module=(()=>{var _scriptName=globalThis.document?.currentScript?.src;return async function(moduleArg={}){var moduleRtn;var m=moduleArg,aa="./this.program",ba="",ca;try{ba=(new URL(".",_scriptName)).href}catch{}ca=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var da=console.log.bind(console),n=console.error.bind(console),q,ea=!1,ha,ia,ja,t,v,B,C,D,F,ka,la,ma,na,oa=!1;
function pa(){var a=qa.buffer;t=new Int8Array(a);B=new Int16Array(a);v=new Uint8Array(a);C=new Uint16Array(a);D=new Int32Array(a);F=new Uint32Array(a);ka=new Float32Array(a);la=new Float64Array(a);ma=new BigInt64Array(a);na=new BigUint64Array(a)}function ra(a){m.onAbort?.(a);a="Aborted("+a+")";n(a);ea=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ja?.(a);throw a;}var sa;
async function ta(a){if(!q)try{var b=await ca(a);return new Uint8Array(b)}catch{}if(a==sa&&q)a=new Uint8Array(q);else throw"both async and sync fetching of the wasm failed";return a}async function ua(a,b){try{var c=await ta(a);return await WebAssembly.instantiate(c,b)}catch(d){n(`failed to asynchronously prepare wasm: ${d}`),ra(d)}}
async function va(a){var b=sa;if(!q)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){n(`wasm streaming compile failed: ${d}`),n("falling back to ArrayBuffer instantiation")}return ua(b,a)}class wa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var xa=a=>{for(;0<a.length;)a.shift()(m)},ya=[],za=[],Aa=()=>{var a=m.preRun.shift();za.push(a)},Ba=!0;class Ca{constructor(a){this.da=a-24}}
var Da=0,Ea=0,Fa={},Ga=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function G(a){return this.fa(F[a>>2])}
var H={},I={},Ha={},Ia=class extends Error{constructor(a){super(a);this.name="InternalError"}},K=(a,b,c)=>{function d(h){h=c(h);if(h.length!==a.length)throw new Ia("Mismatched type converter count");for(var p=0;p<a.length;++p)J(a[p],h[p])}a.forEach(h=>Ha[h]=b);var e=Array(b.length),f=[],g=0;for(let [h,p]of b.entries())I.hasOwnProperty(p)?e[h]=I[p]:(f.push(p),H.hasOwnProperty(p)||(H[p]=[]),H[p].push(()=>{e[h]=I[p];++g;g===f.length&&d(e)}));0===f.length&&d(e)},L=a=>{for(var b="";;){var c=v[a++];if(!c)return b;
b+=String.fromCharCode(c)}},M=class extends Error{constructor(a){super(a);this.name="BindingError"}},Ja=a=>{throw new M(a);};function Ka(a,b,c={}){var d=b.name;if(!a)throw new M(`type "${d}" must have a positive integer typeid pointer`);if(I.hasOwnProperty(a)){if(c.yb)return;throw new M(`Cannot register type '${d}' twice`);}I[a]=b;delete Ha[a];H.hasOwnProperty(a)&&(b=H[a],delete H[a],b.forEach(e=>e()))}function J(a,b,c={}){return Ka(a,b,c)}
var La=(a,b,c)=>{switch(b){case 1:return c?d=>t[d]:d=>v[d];case 2:return c?d=>B[d>>1]:d=>C[d>>1];case 4:return c?d=>D[d>>2]:d=>F[d>>2];case 8:return c?d=>ma[d>>3]:d=>na[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Ma=a=>{throw new M(a.$.ga.ea.name+" instance already deleted");},Na=!1,Oa=()=>{},N=a=>{if(!globalThis.FinalizationRegistry)return N=b=>b,a;Na=new FinalizationRegistry(b=>{b=b.$;--b.count.value;0===b.count.value&&(b.ia?b.na.ta(b.ia):b.ga.ea.ta(b.da))});N=b=>
{var c=b.$;c.ia&&Na.register(b,{$:c},b);return b};Oa=b=>{Na.unregister(b)};return N(a)},Pa=[];function Qa(){}
var Ra=(a,b)=>Object.defineProperty(b,"name",{value:a}),Sa={},Ta=(a,b,c)=>{if(void 0===a[b].wa){var d=a[b];a[b]=function(...e){if(!a[b].wa.hasOwnProperty(e.length))throw new M(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].wa})!`);return a[b].wa[e.length].apply(this,e)};a[b].wa=[];a[b].wa[d.Fa]=d}},Ua=(a,b)=>{if(m.hasOwnProperty(a))throw new M(`Cannot register public name '${a}' twice`);m[a]=b;m[a].Fa=void 0},Va=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,
"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function Wa(a,b,c,d,e,f,g,h){this.name=a;this.constructor=b;this.Ca=c;this.ta=d;this.ka=e;this.tb=f;this.Ka=g;this.rb=h;this.Cb=[]}var Xa=(a,b,c)=>{for(;b!==c;){if(!b.Ka)throw new M(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.Ka(a);b=b.ka}return a},Ya=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a};
function Za(a,b){if(null===b){if(this.Xa)throw new M(`null is not a valid ${this.name}`);return 0}if(!b.$)throw new M(`Cannot pass "${Ya(b)}" as a ${this.name}`);if(!b.$.da)throw new M(`Cannot pass deleted object as a pointer of type ${this.name}`);return Xa(b.$.da,b.$.ga.ea,this.ea)}
function ab(a,b){if(null===b){if(this.Xa)throw new M(`null is not a valid ${this.name}`);if(this.Oa){var c=this.Za();null!==a&&a.push(this.ta,c);return c}return 0}if(!b||!b.$)throw new M(`Cannot pass "${Ya(b)}" as a ${this.name}`);if(!b.$.da)throw new M(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.Na&&b.$.ga.Na)throw new M(`Cannot convert argument of type ${b.$.na?b.$.na.name:b.$.ga.name} to parameter type ${this.name}`);c=Xa(b.$.da,b.$.ga.ea,this.ea);if(this.Oa){if(void 0===
b.$.ia)throw new M("Passing raw pointer to smart pointer is illegal");switch(this.Hb){case 0:if(b.$.na===this)c=b.$.ia;else throw new M(`Cannot convert argument of type ${b.$.na?b.$.na.name:b.$.ga.name} to parameter type ${this.name}`);break;case 1:c=b.$.ia;break;case 2:if(b.$.na===this)c=b.$.ia;else{var d=b.clone();c=this.Db(c,O(()=>d["delete"]()));null!==a&&a.push(this.ta,c)}break;default:throw new M("Unsupporting sharing policy");}}return c}
function bb(a,b){if(null===b){if(this.Xa)throw new M(`null is not a valid ${this.name}`);return 0}if(!b.$)throw new M(`Cannot pass "${Ya(b)}" as a ${this.name}`);if(!b.$.da)throw new M(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.$.ga.Na)throw new M(`Cannot convert argument of type ${b.$.ga.name} to parameter type ${this.name}`);return Xa(b.$.da,b.$.ga.ea,this.ea)}
var cb=(a,b,c)=>{if(b===c)return a;if(void 0===c.ka)return null;a=cb(a,b,c.ka);return null===a?null:c.rb(a)},db={},eb=(a,b)=>{if(void 0===b)throw new M("ptr should not be undefined");for(;a.ka;)b=a.Ka(b),a=a.ka;return db[b]},fb=(a,b)=>{if(!b.ga||!b.da)throw new Ia("makeClassHandle requires ptr and ptrType");if(!!b.na!==!!b.ia)throw new Ia("Both smartPtrType and smartPtr must be specified");b.count={value:1};return N(Object.create(a,{$:{value:b,writable:!0}}))};
function gb(a,b,c,d,e,f,g,h,p,k,l){this.name=a;this.ea=b;this.Xa=c;this.Na=d;this.Oa=e;this.Bb=f;this.Hb=g;this.lb=h;this.Za=p;this.Db=k;this.ta=l;e||void 0!==b.ka?this.ja=ab:(this.ja=d?Za:bb,this.la=null)}var hb=(a,b)=>{if(!m.hasOwnProperty(a))throw new Ia("Replacing nonexistent public symbol");m[a]=b;m[a].Fa=void 0},ib=[],P=(a,b)=>{a=L(a);var c;(c=ib[b])||(ib[b]=c=jb.get(b));if("function"!=typeof c)throw new M(`unknown function pointer with signature ${a}: ${b}`);return c};
class kb extends Error{}var mb=a=>{a=lb(a);var b=L(a);Q(a);return b},nb=(a,b)=>{function c(f){e[f]||I[f]||(Ha[f]?Ha[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new kb(`${a}: `+d.map(mb).join([", "]));},ob=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(F[b+4*d>>2]);return c};function pb(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].la)return!0;return!1}
function qb(a,b,c,d,e,f){var g=b.length;if(2>g)throw new M("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,p=pb(b);c=!b[0].gb;var k=b[0],l=b[1];d=[a,Ja,d,e,Ga,k.fa.bind(k),l?.ja.bind(l)];for(e=2;e<g;++e)k=b[e],d.push(k.ja.bind(k));if(!p)for(e=h?1:2;e<b.length;++e)null!==b[e].la&&d.push(b[e].la);p=pb(b);e=b.length-2;l=[];k=["fn"];h&&k.push("thisWired");for(g=0;g<e;++g)l.push(`arg${g}`),k.push(`arg${g}Wired`);l=l.join(",");k=k.join(",");
l=`return function (${l}) {\n`;p&&(l+="var destructors = [];\n");var u=p?"destructors":"null",r="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");h&&(l+=`var thisWired = toClassParamWire(${u}, this);\n`);for(g=0;g<e;++g){var w=`toArg${g}Wire`;l+=`var arg${g}Wired = ${w}(${u}, arg${g});\n`;r.push(w)}l+=(c||f?"var rv = ":"")+`invoker(${k});\n`;if(p)l+="runDestructors(destructors);\n";else for(g=h?1:2;g<b.length;++g)f=1===g?"thisWired":"arg"+(g-2)+"Wired",
null!==b[g].la&&(l+=`${f}_dtor(${f});\n`,r.push(`${f}_dtor`));c&&(l+="var ret = fromRetWire(rv);\nreturn ret;\n");b=(new Function(r,l+"}\n"))(...d);return Ra(a,b)}
var rb=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},sb=[],R=[0,1,,1,null,1,!0,1,!1,1],tb=a=>{9<a&&0===--R[a+1]&&(R[a]=void 0,sb.push(a))},ub=a=>{if(!a)throw new M(`Cannot use deleted val. handle = ${a}`);return R[a]},O=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=sb.pop()||R.length;R[b]=a;R[b+1]=1;return b}},vb={name:"emscripten::val",fa:a=>{var b=ub(a);tb(a);return b},ja:(a,b)=>O(b),qa:G,la:null},wb=(a,b,c)=>{switch(b){case 1:return c?
function(d){return this.fa(t[d])}:function(d){return this.fa(v[d])};case 2:return c?function(d){return this.fa(B[d>>1])}:function(d){return this.fa(C[d>>1])};case 4:return c?function(d){return this.fa(D[d>>2])}:function(d){return this.fa(F[d>>2])};default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},xb=(a,b)=>{var c=I[a];if(void 0===c)throw a=`${b} has unknown type ${mb(a)}`,new M(a);return c},yb=(a,b)=>{switch(b){case 4:return function(c){return this.fa(ka[c>>2])};case 8:return function(c){return this.fa(la[c>>
3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},zb=Object.assign({optional:!0},vb),S=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(c>=d)break;b[c++]=g}else if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-
e},Ab=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Bb=globalThis.TextDecoder&&new TextDecoder,Cb=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},T=(a,b=0,c,d)=>{c=Cb(a,b,c,d);if(16<c-b&&a.buffer&&Bb)return Bb.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|
f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Db=globalThis.TextDecoder?new TextDecoder("utf-16le"):void 0,Eb=(a,b,c)=>{a>>=1;b=Cb(C,a,b/2,c);if(16<b-a&&Db)return Db.decode(C.subarray(a,b));for(c="";a<b;++a)c+=String.fromCharCode(C[a]);return c},Fb=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)B[b>>1]=a.charCodeAt(e),b+=2;B[b>>1]=0;
return b-d},Gb=a=>2*a.length,Hb=(a,b,c)=>{var d="";a>>=2;for(var e=0;!(e>=b/4);e++){var f=F[a+e];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},Ib=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.codePointAt(e);65535<f&&e++;D[b>>2]=f;b+=4;if(b+4>c)break}D[b>>2]=0;return b-d},Jb=a=>{for(var b=0,c=0;c<a.length;++c)65535<a.codePointAt(c)&&c++,b+=4;return b},Kb=0,Lb=[],Mb=a=>{var b=Lb.length;Lb.push(a);return b},Nb=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=
xb(F[b+4*d>>2],`parameter ${d}`);return c},Ob=(a,b,c)=>{var d=[];a=a(d,c);d.length&&(F[b>>2]=O(d));return a},Pb={},Qb=a=>{var b=Pb[a];return void 0===b?L(a):b},Rb={},Sb=a=>{if(!(a instanceof wa||"unwind"==a))throw a;},Tb=a=>{ha=a;Ba||0<Kb||(m.onExit?.(a),ea=!0);throw new wa(a);},Ub=a=>{if(!ea)try{if(a(),!(Ba||0<Kb))try{ha=a=ha,Tb(a)}catch(b){Sb(b)}}catch(b){Sb(b)}},Vb={},Xb=()=>{if(!Wb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??
"C").replace("-","_")+".UTF-8",_:aa||"./this.program"},b;for(b in Vb)void 0===Vb[b]?delete a[b]:a[b]=Vb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Wb=c}return Wb},Wb,Yb=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Zb=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Yb(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},$b=a=>{var b=
/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},bc=()=>a=>crypto.getRandomValues(a),cc=a=>{(cc=bc())(a)},dc=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Yb(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},ec=[],fc=[];
function gc(a,b){fc[a]={input:[],output:[],Ea:b};hc(a,ic)}
var ic={open(a){var b=fc[a.node.Ra];if(!b)throw new U(43);a.oa=b;a.seekable=!1},close(a){a.oa.Ea.Ma(a.oa)},Ma(a){a.oa.Ea.Ma(a.oa)},read(a,b,c,d){if(!a.oa||!a.oa.Ea.fb)throw new U(60);for(var e=0,f=0;f<d;f++){try{var g=a.oa.Ea.fb(a.oa)}catch(h){throw new U(29);}if(void 0===g&&0===e)throw new U(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.ya=Date.now());return e},write(a,b,c,d){if(!a.oa||!a.oa.Ea.Ya)throw new U(60);try{for(var e=0;e<d;e++)a.oa.Ea.Ya(a.oa,b[c+e])}catch(f){throw new U(29);
}d&&(a.node.pa=a.node.ma=Date.now());return e}},jc={fb(){a:{if(!ec.length){var a=null;globalThis.window?.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){var b=null;break a}b=Array(Ab(a)+1);a=S(a,b,0,b.length);b.length=a;ec=b}b=ec.shift()}return b},Ya(a,b){null===b||10===b?(da(T(a.output)),a.output=[]):0!=b&&a.output.push(b)},Ma(a){0<a.output?.length&&(da(T(a.output)),a.output=[])},Vb(){return{Nb:25856,Pb:5,Mb:191,Ob:35387,Lb:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0]}},Wb(){return 0},Xb(){return[24,80]}},kc={Ya(a,b){null===b||10===b?(n(T(a.output)),a.output=[]):0!=b&&a.output.push(b)},Ma(a){0<a.output?.length&&(n(T(a.output)),a.output=[])}},V={sa:null,va(){return V.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new U(63);V.sa||(V.sa={dir:{node:{xa:V.ba.xa,ua:V.ba.ua,Ha:V.ba.Ha,Pa:V.ba.Pa,mb:V.ba.mb,ob:V.ba.ob,nb:V.ba.nb,$a:V.ba.$a,Sa:V.ba.Sa},stream:{ra:V.ca.ra}},file:{node:{xa:V.ba.xa,ua:V.ba.ua},
stream:{ra:V.ca.ra,read:V.ca.read,write:V.ca.write,ib:V.ca.ib,kb:V.ca.kb}},link:{node:{xa:V.ba.xa,ua:V.ba.ua,Ja:V.ba.Ja},stream:{}},bb:{node:{xa:V.ba.xa,ua:V.ba.ua},stream:lc}});c=mc(a,b,c,d);16384===(c.mode&61440)?(c.ba=V.sa.dir.node,c.ca=V.sa.dir.stream,c.aa={}):32768===(c.mode&61440)?(c.ba=V.sa.file.node,c.ca=V.sa.file.stream,c.ha=0,c.aa=null):40960===(c.mode&61440)?(c.ba=V.sa.link.node,c.ca=V.sa.link.stream):8192===(c.mode&61440)&&(c.ba=V.sa.bb.node,c.ca=V.sa.bb.stream);c.ya=c.pa=c.ma=Date.now();
a&&(a.aa[b]=c,a.ya=a.pa=a.ma=c.ya);return c},Sb(a){return a.aa?a.aa.subarray?a.aa.subarray(0,a.ha):new Uint8Array(a.aa):new Uint8Array(0)},ba:{xa(a){var b={};b.Qb=8192===(a.mode&61440)?a.id:1;b.Ub=a.id;b.mode=a.mode;b.Yb=1;b.uid=0;b.Tb=0;b.Ra=a.Ra;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.ha:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.ya=new Date(a.ya);b.pa=new Date(a.pa);b.ma=new Date(a.ma);b.pb=4096;b.Kb=Math.ceil(b.size/b.pb);return b},ua(a,b){for(var c of["mode",
"atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.ha!=b&&(0==b?(a.aa=null,a.ha=0):(c=a.aa,a.aa=new Uint8Array(b),c&&a.aa.set(c.subarray(0,Math.min(b,a.ha))),a.ha=b)))},Ha(){V.Ta||(V.Ta=new U(44),V.Ta.stack="<generic error, no stack>");throw V.Ta;},Pa(a,b,c,d){return V.createNode(a,b,c,d)},mb(a,b,c){try{var d=nc(b,c)}catch(f){}if(d){if(16384===(a.mode&61440))for(var e in d.aa)throw new U(55);e=oc(d.parent.id,d.name);if(W[e]===d)W[e]=d.Da;else for(e=W[e];e;){if(e.Da===d){e.Da=
d.Da;break}e=e.Da}}delete a.parent.aa[a.name];b.aa[c]=a;a.name=c;b.ma=b.pa=a.parent.ma=a.parent.pa=Date.now()},ob(a,b){delete a.aa[b];a.ma=a.pa=Date.now()},nb(a,b){var c=nc(a,b),d;for(d in c.aa)throw new U(55);delete a.aa[b];a.ma=a.pa=Date.now()},$a(a){return[".","..",...Object.keys(a.aa)]},Sa(a,b,c){a=V.createNode(a,b,41471,0);a.link=c;return a},Ja(a){if(40960!==(a.mode&61440))throw new U(28);return a.link}},ca:{read(a,b,c,d,e){var f=a.node.aa;if(e>=a.node.ha)return 0;a=Math.min(a.node.ha-e,d);if(8<
a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===t.buffer&&(f=!1);if(!d)return 0;a=a.node;a.pa=a.ma=Date.now();if(b.subarray&&(!a.aa||a.aa.subarray)){if(f)return a.aa=b.subarray(c,c+d),a.ha=d;if(0===a.ha&&0===e)return a.aa=b.slice(c,c+d),a.ha=d;if(e+d<=a.ha)return a.aa.set(b.subarray(c,c+d),e),d}f=e+d;var g=a.aa?a.aa.length:0;g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>0),0!=g&&(f=Math.max(f,256)),g=a.aa,a.aa=new Uint8Array(f),0<a.ha&&
a.aa.set(g.subarray(0,a.ha),0));if(a.aa.subarray&&b.subarray)a.aa.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.aa[e+f]=b[c+f];a.ha=Math.max(a.ha,e+d);return d},ra(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.ha);if(0>b)throw new U(28);return b},ib(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new U(43);a=a.node.aa;if(e&2||!a||a.buffer!==t.buffer){d=!0;ra();e=void 0;if(!e)throw new U(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,
c,c+b);t.set(a,e)}}else d=!1,e=a.byteOffset;return{da:e,Jb:d}},kb(a,b,c,d){V.ca.write(a,b,0,d,c,!1);return 0}}},pc=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},qc=null,rc={},sc=[],tc=1,W=null,uc=!1,vc=!0,wc={},U=class{name="ErrnoError";constructor(a){this.Aa=a}},xc=class{La={};node=null;get flags(){return this.La.flags}set flags(a){this.La.flags=a}get position(){return this.La.position}set position(a){this.La.position=a}},yc=class{ba={};ca={};Qa=null;constructor(a,b,c,d){a||=this;this.parent=
a;this.va=a.va;this.id=tc++;this.name=b;this.mode=c;this.Ra=d;this.ya=this.pa=this.ma=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}};
function X(a,b={}){if(!a)throw new U(44);b.Va??(b.Va=!0);"/"===a.charAt(0)||(a="//"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(h=>!!h);for(var d=qc,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if("."!==a[f])if(".."===a[f])if(e=$b(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=Zb(e+"/"+a[f]);try{d=nc(d,a[f])}catch(h){if(44===h?.Aa&&g&&b.Ab)return{path:e};throw h;}!d.Qa||g&&!b.Va||(d=d.Qa.root);if(40960===(d.mode&61440)&&(!g||b.Ua)){if(!d.ba.Ja)throw new U(52);
d=d.ba.Ja(d);"/"===d.charAt(0)||(d=$b(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new U(32);}function oc(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%W.length}function nc(a,b){var c=16384===(a.mode&61440)?(c=zc(a,"x"))?c:a.ba.Ha?0:2:54;if(c)throw new U(c);for(c=W[oc(a.id,b)];c;c=c.Da){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.ba.Ha(a,b)}
function mc(a,b,c,d){a=new yc(a,b,c,d);b=oc(a.parent.id,a.name);a.Da=W[b];return W[b]=a}function Ac(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function zc(a,b){if(vc)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Bc(a,b){if(16384!==(a.mode&61440))return 54;try{return nc(a,b),20}catch(c){}return zc(a,"wx")}function Cc(a){a=sc[a];if(!a)throw new U(8);return a}
function Dc(a,b){var c=null?.ca.ua,d=c?null:a;c??=a.ba.ua;if(!c)throw new U(63);c(d,b)}var lc={open(a){a.ca=rc[a.node.Ra].ca;a.ca.open?.(a)},ra(){throw new U(70);}};function hc(a,b){rc[a]={ca:b}}function Ec(a,b){var c="/"===b;if(c&&qc)throw new U(10);if(!c&&b){var d=X(b,{Va:!1});b=d.path;d=d.node;if(d.Qa)throw new U(10);if(16384!==(d.mode&61440))throw new U(54);}b={type:a,Zb:{},jb:b,zb:[]};a=a.va(b);a.va=b;b.root=a;c?qc=a:d&&(d.Qa=b,d.va&&d.va.zb.push(b))}
function Fc(a,b,c){var d=X(a,{parent:!0}).node;a=a&&a.match(/([^\/]+|\/)\/*$/)[1];if(!a)throw new U(28);if("."===a||".."===a)throw new U(20);var e=Bc(d,a);if(e)throw new U(e);if(!d.ba.Pa)throw new U(63);return d.ba.Pa(d,a,b,c)}function Y(a){return Fc(a,16895,0)}function Gc(a,b,c){"undefined"==typeof c&&(c=b,b=438);Fc(a,b|8192,c)}
function Hc(a,b){if(!dc(a))throw new U(44);var c=X(b,{parent:!0}).node;if(!c)throw new U(44);b=b&&b.match(/([^\/]+|\/)\/*$/)[1];var d=Bc(c,b);if(d)throw new U(d);if(!c.ba.Sa)throw new U(63);c.ba.Sa(c,b,a)}
function Ic(a,b){if(""===a)throw new U(44);if("string"==typeof b){var c={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof c)throw Error(`Unknown file open mode: ${b}`);b=c}c=b&64?33206:0;if("object"==typeof a)var d=a;else{var e=a.endsWith("/");a=X(a,{Ua:!(b&131072),Ab:!0});d=a.node;a=a.path}var f=!1;if(b&64)if(d){if(b&128)throw new U(20);}else{if(e)throw new U(31);d=Fc(a,c|511,0);f=!0}if(!d)throw new U(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&16384!==(d.mode&61440))throw new U(54);
if(!f&&(e=d?40960===(d.mode&61440)?32:16384===(d.mode&61440)&&("r"!==Ac(b)||b&576)?31:zc(d,Ac(b)):44))throw new U(e);if(b&512&&!f){e=d;e="string"==typeof e?X(e,{Ua:!0}).node:e;if(16384===(e.mode&61440))throw new U(31);if(32768!==(e.mode&61440))throw new U(28);var g=zc(e,"w");if(g)throw new U(g);Dc(e,{size:0,timestamp:Date.now()})}b&=-131713;a:for(e=d;;){if(e===e.parent){e=e.va.jb;var h=h?"/"!==e[e.length-1]?`${e}/${h}`:e+h:e;break a}h=h?`${e.name}/${h}`:e.name;e=e.parent}h={node:d,path:h,flags:b,
seekable:!0,position:0,ca:d.ca,Ib:[],error:!1};e=-1;h=Object.assign(new xc,h);if(-1==e)a:{for(e=0;4096>=e;e++)if(!sc[e])break a;throw new U(33);}h.Ba=e;sc[e]=h;h.ca.open&&h.ca.open(h);f&&(c&=511,d="string"==typeof d?X(d,{Ua:!0}).node:d,Dc(d,{mode:c&4095|d.mode&-4096,ma:Date.now(),Rb:void 0}));!m.logReadFiles||b&1||a in wc||(wc[a]=1)}function Jc(a,b,c){if(null===a.Ba)throw new U(8);if(!a.seekable||!a.ca.ra)throw new U(70);if(0!=c&&1!=c&&2!=c)throw new U(28);a.position=a.ca.ra(a,b,c);a.Ib=[]}
function Z(a,b,c){a=Zb("/dev/"+a);var d=pc(!!b,!!c);Z.hb??(Z.hb=64);var e=Z.hb++<<8|0;hc(e,{open(f){f.seekable=!1},close(){c?.buffer?.length&&c(10)},read(f,g,h,p){for(var k=0,l=0;l<p;l++){try{var u=b()}catch(r){throw new U(29);}if(void 0===u&&0===k)throw new U(6);if(null===u||void 0===u)break;k++;g[h+l]=u}k&&(f.node.ya=Date.now());return k},write(f,g,h,p){for(var k=0;k<p;k++)try{c(g[h+k])}catch(l){throw new U(29);}p&&(f.node.pa=f.node.ma=Date.now());return k}});Gc(a,d,e)}
var Kc={},Oc=(a,b,c,d)=>{var e={string:k=>{var l=0;if(null!==k&&void 0!==k&&0!==k){l=Ab(k)+1;var u=Lc(l);S(k,v,u,l);l=u}return l},array:k=>{var l=Lc(k.length);t.set(k,l);return l}};a=m["_"+a];var f=[],g=0;if(d)for(var h=0;h<d.length;h++){var p=e[c[h]];p?(0===g&&(g=Mc()),f[h]=p(d[h])):f[h]=d[h]}c=a(...f);return c=function(k){0!==g&&Nc(g);return"string"===b?k?T(v,k):"":"boolean"===b?!!k:k}(c)};
(()=>{let a=Qa.prototype;Object.assign(a,{isAliasOf:function(c){if(!(this instanceof Qa&&c instanceof Qa))return!1;var d=this.$.ga.ea,e=this.$.da;c.$=c.$;var f=c.$.ga.ea;for(c=c.$.da;d.ka;)e=d.Ka(e),d=d.ka;for(;f.ka;)c=f.Ka(c),f=f.ka;return d===f&&e===c},clone:function(){this.$.da||Ma(this);if(this.$.Ia)return this.$.count.value+=1,this;var c=N,d=Object,e=d.create,f=Object.getPrototypeOf(this),g=this.$;c=c(e.call(d,f,{$:{value:{count:g.count,Ga:g.Ga,Ia:g.Ia,da:g.da,ga:g.ga,ia:g.ia,na:g.na}}}));c.$.count.value+=
1;c.$.Ga=!1;return c},["delete"](){this.$.da||Ma(this);if(this.$.Ga&&!this.$.Ia)throw new M("Object already scheduled for deletion");Oa(this);var c=this.$;--c.count.value;0===c.count.value&&(c.ia?c.na.ta(c.ia):c.ga.ea.ta(c.da));this.$.Ia||(this.$.ia=void 0,this.$.da=void 0)},isDeleted:function(){return!this.$.da},deleteLater:function(){this.$.da||Ma(this);if(this.$.Ga&&!this.$.Ia)throw new M("Object already scheduled for deletion");Pa.push(this);this.$.Ga=!0;return this}});const b=Symbol.dispose;
b&&(a[b]=a["delete"])})();
Object.assign(gb.prototype,{ub(a){this.lb&&(a=this.lb(a));return a},cb(a){this.ta?.(a)},qa:G,fa:function(a){function b(){return this.Oa?fb(this.ea.Ca,{ga:this.Bb,da:c,na:this,ia:a}):fb(this.ea.Ca,{ga:this,da:a})}var c=this.ub(a);if(!c)return this.cb(a),null;var d=eb(this.ea,c);if(void 0!==d){if(0===d.$.count.value)return d.$.da=c,d.$.ia=a,d.clone();d=d.clone();this.cb(a);return d}d=this.ea.tb(c);d=Sa[d];if(!d)return b.call(this);d=this.Na?d.qb:d.pointerType;var e=cb(c,this.ea,d.ea);return null===
e?b.call(this):this.Oa?fb(d.ea.Ca,{ga:d,da:e,na:this,ia:a}):fb(d.ea.Ca,{ga:d,da:e})}});W=Array(4096);Ec(V,"/");Y("/tmp");Y("/home");Y("/home/web_user");(function(){Y("/dev");hc(259,{read:()=>0,write:(d,e,f,g)=>g,ra:()=>0});Gc("/dev/null",259);gc(1280,jc);gc(1536,kc);Gc("/dev/tty",1280);Gc("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(cc(a),b=a.byteLength);return a[--b]};Z("random",c);Z("urandom",c);Y("/dev/shm");Y("/dev/shm/tmp")})();
(function(){Y("/proc");var a=Y("/proc/self");Y("/proc/self/fd");Ec({va(){var b=mc(a,"fd",16895,73);b.ca={ra:V.ca.ra};b.ba={Ha(c,d){c=+d;var e=Cc(c);c={parent:null,va:{jb:"fake"},ba:{Ja:()=>e.path},id:c+1};return c.parent=c},$a(){return Array.from(sc.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();m.noExitRuntime&&(Ba=m.noExitRuntime);m.print&&(da=m.print);m.printErr&&(n=m.printErr);m.wasmBinary&&(q=m.wasmBinary);m.thisProgram&&(aa=m.thisProgram);
if(m.preInit)for("function"==typeof m.preInit&&(m.preInit=[m.preInit]);0<m.preInit.length;)m.preInit.shift()();m.ccall=Oc;m.cwrap=(a,b,c,d)=>{var e=!c||c.every(f=>"number"===f||"boolean"===f);return"string"!==b&&e&&!d?m["_"+a]:(...f)=>Oc(a,b,c,f,d)};
var lb,Pc,Qc,Rc,Q,Nc,Lc,Mc,qa,jb,Sc={s:(a,b,c)=>{var d=new Ca(a);F[d.da+16>>2]=0;F[d.da+4>>2]=b;F[d.da+8>>2]=c;Da=a;Ea++;throw Da;},G:()=>ra(""),n:a=>{var b=Fa[a];delete Fa[a];var c=b.Za,d=b.ta,e=b.eb,f=e.map(g=>g.xb).concat(e.map(g=>g.Fb));K([a],f,g=>{var h={},p,k;for([p,k]of e.entries()){const l=g[p],u=k.vb,r=k.wb,w=g[p+e.length],x=k.Eb,A=k.Gb;h[k.sb]={read:z=>l.fa(u(r,z)),write:(z,E)=>{var y=[];x(A,z,w.ja(y,E));Ga(y)},optional:l.optional}}return[{name:b.name,fa:l=>{var u={},r;for(r in h)u[r]=h[r].read(l);
d(l);return u},ja:(l,u)=>{for(var r in h)if(!(r in u||h[r].optional))throw new TypeError(`Missing field: "${r}"`);var w=c();for(r in h)h[r].write(w,u[r]);null!==l&&l.push(d,w);return w},qa:G,la:d}]})},q:(a,b,c,d,e)=>{b=L(b);d=0n===d;let f=g=>g;if(d){const g=8*c;f=h=>BigInt.asUintN(g,h);e=f(e)}J(a,{name:b,fa:f,ja:(g,h)=>{"number"==typeof h&&(h=BigInt(h));return h},qa:La(b,c,!d),la:null})},t:(a,b,c,d)=>{b=L(b);J(a,{name:b,fa:function(e){return!!e},ja:function(e,f){return f?c:d},qa:function(e){return this.fa(v[e])},
la:null})},g:(a,b,c,d,e,f,g,h,p,k,l,u,r)=>{l=L(l);f=P(e,f);h&&=P(g,h);k&&=P(p,k);r=P(u,r);var w=Va(l);Ua(w,function(){nb(`Cannot construct ${l} due to unbound types`,[d])});K([a,b,c],d?[d]:[],x=>{x=x[0];if(d){var A=x.ea;var z=A.Ca}else z=Qa.prototype;x=Ra(l,function(...$a){if(Object.getPrototypeOf(this)!==E)throw new M(`Use 'new' to construct ${l}`);if(void 0===y.za)throw new M(`${l} has no accessible constructor`);var ac=y.za[$a.length];if(void 0===ac)throw new M(`Tried to invoke ctor of ${l} with invalid number of parameters (${$a.length}) - expected (${Object.keys(y.za).toString()}) parameters instead!`);
return ac.apply(this,$a)});var E=Object.create(z,{constructor:{value:x}});x.prototype=E;var y=new Wa(l,x,E,r,A,f,h,k);if(y.ka){var fa;(fa=y.ka).ab??(fa.ab=[]);y.ka.ab.push(y)}A=new gb(l,y,!0,!1,!1);fa=new gb(l+"*",y,!1,!1,!1);z=new gb(l+" const*",y,!1,!0,!1);Sa[a]={pointerType:fa,qb:z};hb(w,x);return[A,fa,z]})},h:(a,b,c,d,e,f)=>{var g=ob(b,c);e=P(d,e);K([],[a],h=>{h=h[0];var p=`constructor ${h.name}`;void 0===h.ea.za&&(h.ea.za=[]);if(void 0!==h.ea.za[b-1])throw new M(`Cannot register multiple constructors with identical number of parameters (${b-
1}) for class '${h.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);h.ea.za[b-1]=()=>{nb(`Cannot construct ${h.name} due to unbound types`,g)};K([],g,k=>{k.splice(1,0,null);h.ea.za[b-1]=qb(p,k,null,e,f);return[]});return[]})},a:(a,b,c,d,e,f,g,h,p)=>{var k=ob(c,d);b=L(b);b=rb(b);f=P(e,f);K([],[a],l=>{function u(){nb(`Cannot call ${r} due to unbound types`,k)}l=l[0];var r=`${l.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);h&&l.ea.Cb.push(b);
var w=l.ea.Ca,x=w[b];void 0===x||void 0===x.wa&&x.className!==l.name&&x.Fa===c-2?(u.Fa=c-2,u.className=l.name,w[b]=u):(Ta(w,b,r),w[b].wa[c-2]=u);K([],k,A=>{A=qb(r,A,l,f,g,p);void 0===w[b].wa?(A.Fa=c-2,w[b]=A):w[b].wa[c-2]=A;return[]});return[]})},N:a=>J(a,vb),j:(a,b,c,d)=>{function e(){}b=L(b);e.values={};J(a,{name:b,constructor:e,fa:function(f){return this.constructor.values[f]},ja:(f,g)=>g.value,qa:wb(b,c,d),la:null});Ua(b,e)},i:(a,b,c)=>{var d=xb(a,"enum");b=L(b);a=d.constructor;d=Object.create(d.constructor.prototype,
{value:{value:c},constructor:{value:Ra(`${d.name}_${b}`,function(){})}});a.values[c]=d;a[b]=d},p:(a,b,c)=>{b=L(b);J(a,{name:b,fa:d=>d,ja:(d,e)=>e,qa:yb(b,c),la:null})},c:(a,b,c,d,e)=>{b=L(b);let f=h=>h;if(0===d){var g=32-8*c;f=h=>h<<g>>>g;e=f(e)}J(a,{name:b,fa:f,ja:(h,p)=>p,qa:La(b,c,0!==d),la:null})},b:(a,b,c)=>{function d(f){return new e(t.buffer,F[f+4>>2],F[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];
c=L(c);J(a,{name:c,fa:d,qa:d},{yb:!0})},m:a=>{J(a,zb)},O:(a,b)=>{b=L(b);J(a,{name:b,fa(c){var d=(d=c+4)?T(v,d,F[c>>2],!0):"";Q(c);return d},ja(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new M("Cannot pass non-string to std::string");var f=e?Ab(d):d.length;var g=Qc(4+f+1),h=g+4;F[g>>2]=f;e?S(d,v,h,f+1):v.set(d,h);null!==c&&c.push(Q,g);return g},qa:G,la(c){Q(c)}})},k:(a,b,c)=>{c=L(c);if(2===b){var d=Eb;var e=
Fb;var f=Gb}else d=Hb,e=Ib,f=Jb;J(a,{name:c,fa:g=>{var h=d(g+4,F[g>>2]*b,!0);Q(g);return h},ja:(g,h)=>{if("string"!=typeof h)throw new M(`Cannot pass non-string to C++ string type ${c}`);var p=f(h),k=Qc(4+p+b);F[k>>2]=p/b;e(h,k+4,p+b);null!==g&&g.push(Q,k);return k},qa:G,la(g){Q(g)}})},o:(a,b,c,d,e,f)=>{Fa[a]={name:L(b),Za:P(c,d),ta:P(e,f),eb:[]}},f:(a,b,c,d,e,f,g,h,p,k)=>{Fa[a].eb.push({sb:L(b),xb:c,vb:P(d,e),wb:f,Fb:g,Eb:P(h,p),Gb:k})},u:(a,b)=>{b=L(b);J(a,{gb:!0,name:b,fa:()=>{},ja:()=>{}})},x:()=>
{Ba=!1;Kb=0},e:(a,b,c)=>{var [d,...e]=Nb(a,b);b=d.ja.bind(d);var f=e.map(p=>p.qa.bind(p));a--;var g={toValue:ub};a=f.map((p,k)=>{var l=`argFromPtr${k}`;g[l]=p;return`${l}(args${k?"+"+8*k:""})`});switch(c){case 0:var h="toValue(handle)";break;case 2:h="new (toValue(handle))";break;case 3:h="";break;case 1:g.getStringOrSymbol=Qb,h="toValue(handle)[getStringOrSymbol(methodName)]"}h+=`(${a})`;d.gb||(g.toReturnWire=b,g.emval_returnValue=Ob,h=`return emval_returnValue(toReturnWire, destructorsRef, ${h})`);
h=`return function (handle, methodName, destructorsRef, args) {\n  ${h}\n  }`;c=(new Function(Object.keys(g),h))(...Object.values(g));h=`methodCaller<(${e.map(p=>p.name)}) => ${d.name}>`;return Mb(Ra(h,c))},M:tb,L:a=>{if(!a)return O(globalThis);a=Qb(a);return O(globalThis[a])},r:(a,b)=>{a=ub(a);b=ub(b);return O(a[b])},l:a=>{9<a&&(R[a+1]+=1)},d:(a,b,c,d,e)=>Lb[a](b,c,d,e),K:a=>O(Qb(a)),v:a=>{var b=ub(a);Ga(b);tb(a)},y:(a,b)=>{Rb[a]&&(clearTimeout(Rb[a].id),delete Rb[a]);if(!b)return 0;var c=setTimeout(()=>
{delete Rb[a];Ub(()=>Rc(a,performance.now()))},b);Rb[a]={id:c,$b:b};return 0},A:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();F[a>>2]=60*Math.max(f,e);D[b>>2]=Number(f!=e);b=g=>{var h=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(h/60)).padStart(2,"0")}${String(h%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(S(a,v,c,17),S(b,v,d,17)):(S(a,v,d,17),S(b,v,c,17))},H:function(a,b,c){if(!(0<=a&&3>=a))return 28;ma[c>>3]=BigInt(Math.round(1E6*
(0===a?Date.now():performance.now())));return 0},I:a=>{var b=v.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-qa.buffer.byteLength+65535)/65536|0;try{qa.grow(d);pa();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},B:(a,b)=>{var c=0,d=0,e;for(e of Xb()){var f=b+c;F[a+d>>2]=f;c+=S(e,v,f,Infinity)+1;d+=4}return 0},C:(a,b)=>{var c=Xb();F[a>>2]=c.length;a=0;for(var d of c)a+=
Ab(d)+1;F[b>>2]=a;return 0},D:function(a){try{var b=Cc(a);if(null===b.Ba)throw new U(8);b.Wa&&(b.Wa=null);try{b.ca.close&&b.ca.close(b)}catch(c){throw c;}finally{sc[b.Ba]=null}b.Ba=null;return 0}catch(c){if("undefined"==typeof Kc||"ErrnoError"!==c.name)throw c;return c.Aa}},F:function(a,b,c,d){try{a:{var e=Cc(a);a=b;for(var f,g=b=0;g<c;g++){var h=F[a>>2],p=F[a+4>>2];a+=8;var k=e,l=h,u=p,r=f,w=t;if(0>u||0>r)throw new U(28);if(null===k.Ba)throw new U(8);if(1===(k.flags&2097155))throw new U(8);if(16384===
(k.node.mode&61440))throw new U(31);if(!k.ca.read)throw new U(28);var x="undefined"!=typeof r;if(!x)r=k.position;else if(!k.seekable)throw new U(70);var A=k.ca.read(k,w,l,u,r);x||(k.position+=A);var z=A;if(0>z){var E=-1;break a}b+=z;if(z<p)break;"undefined"!=typeof f&&(f+=z)}E=b}F[d>>2]=E;return 0}catch(y){if("undefined"==typeof Kc||"ErrnoError"!==y.name)throw y;return y.Aa}},E:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=Cc(a);Jc(e,b,c);
ma[d>>3]=BigInt(e.position);e.Wa&&0===b&&0===c&&(e.Wa=null);return 0}catch(f){if("undefined"==typeof Kc||"ErrnoError"!==f.name)throw f;return f.Aa}},J:function(a,b,c,d){try{a:{var e=Cc(a);a=b;for(var f,g=b=0;g<c;g++){var h=F[a>>2],p=F[a+4>>2];a+=8;var k=e,l=h,u=p,r=f,w=t;if(0>u||0>r)throw new U(28);if(null===k.Ba)throw new U(8);if(0===(k.flags&2097155))throw new U(8);if(16384===(k.node.mode&61440))throw new U(31);if(!k.ca.write)throw new U(28);k.seekable&&k.flags&1024&&Jc(k,0,2);var x="undefined"!=
typeof r;if(!x)r=k.position;else if(!k.seekable)throw new U(70);var A=k.ca.write(k,w,l,u,r,void 0);x||(k.position+=A);var z=A;if(0>z){var E=-1;break a}b+=z;if(z<p)break;"undefined"!=typeof f&&(f+=z)}E=b}F[d>>2]=E;return 0}catch(y){if("undefined"==typeof Kc||"ErrnoError"!==y.name)throw y;return y.Aa}},w:Tb,z:function(a,b){try{return cc(v.subarray(a,a+b)),0}catch(c){if("undefined"==typeof Kc||"ErrnoError"!==c.name)throw c;return c.Aa}}},Tc;
Tc=await (async function(){function a(c){c=Tc=c.exports;lb=c.R;Pc=m._main=c.S;Qc=c.U;Rc=c.V;Q=c.W;Nc=c.X;Lc=c.Y;Mc=c.Z;qa=c.P;jb=c.T;pa();return Tc}var b={a:Sc};if(m.instantiateWasm)return new Promise(c=>{m.instantiateWasm(b,(d,e)=>{c(a(d,e))})});sa??=m.locateFile?m.locateFile("splendor.wasm",ba):ba+"splendor.wasm";return a((await va(b)).instance)}());
(function(){function a(){m.calledRun=!0;if(!ea){oa=!0;if(!m.noFSInit&&!uc){var b,c;uc=!0;b??=m.stdin;c??=m.stdout;d??=m.stderr;b?Z("stdin",b):Hc("/dev/tty","/dev/stdin");c?Z("stdout",null,c):Hc("/dev/tty","/dev/stdout");d?Z("stderr",null,d):Hc("/dev/tty1","/dev/stderr");Ic("/dev/stdin",0);Ic("/dev/stdout",1);Ic("/dev/stderr",1)}Tc.Q();vc=!1;ia?.(m);m.onRuntimeInitialized?.();if(!m.noInitialRun){var d=Pc;try{var e=d(0,0);ha=e;Tb(e)}catch(f){Sb(f)}}if(m.postRun)for("function"==typeof m.postRun&&(m.postRun=
[m.postRun]);m.postRun.length;)e=m.postRun.shift(),ya.push(e);xa(ya)}}if(m.preRun)for("function"==typeof m.preRun&&(m.preRun=[m.preRun]);m.preRun.length;)Aa();xa(za);m.setStatus?(m.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>m.setStatus(""),1);a()},1)):a()})();oa?moduleRtn=m:moduleRtn=new Promise((a,b)=>{ia=a;ja=b});
;return moduleRtn}})();if(typeof exports==="object"&&typeof module==="object"){module.exports=Module;module.exports.default=Module}else if(typeof define==="function"&&define["amd"])define([],()=>Module);
